name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build app and deploy to Azure
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-output
          path: ./build-output
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        working-directory: "./build-ouput"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "." 
