name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build app and deploy to Azure
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        working-directory: "./code"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "." 
