name: Deploy

on:
  push:
    branches:
      - 2022-rewrite

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "marius-build-and-deploy-2022" 
          heroku_email: "mariuskalvo30@gmail.com"